#!/bin/bash
source lib/gitlab-runner.bash


if ! check_mandatory_config_values; then
    juju-log INFO "Missing mandatory config."
    status-set blocked "Missing mandatory config."
    exit 0
fi

# Only re/configure if not registered already.
# The gitlab-runner API does not support reconfiguration anyway.

if ! gitlab-runner verify -n "$(hostname)"; then
  _gitlabserver=$(config-get gitlab-server)

  if gitlab-runner-register; then
	  juju-log INFO "Ready (Registered with $_gitlabserver)"
  else
	  juju-log ERROR "Failed in registration of runner. Bailing out."
	  exit 1
  fi
else
  juju-log INFO "This runner is already registered. No action taken."
  status-set active "Ready (Already registered.)"
fi

hooks/update-status
