#!/bin/bash
# INSTALL PROCESS DOCUMENTED HERE
# https://gitlab.com/gitlab-org/gitlab-runner/blob/master/docs/install/linux-repository.md

source lib/gitlab-runner.bash

# Install official gitlab repo
curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

export GITLAB_RUNNER_DISABLE_SKEL=true
sudo -E apt-get -y install gitlab-runner docker.io

# Install and start using a custom systemd startup (has metrics)
cp templates/etc/systemd/system/gitlab-runner.service /etc/systemd/system/gitlab-runner.service 
systemctl daemon-reload
systemctl restart gitlab-runner.service

# Fire up docker
systemctl start docker.service

# Set the version
set-gitlab-runner-version
