#!/bin/bash
source lib/gitlab-runner.bash

# Just check the local config against the assumed name (hostname)
if gitlab-runner verify -n "$(hostname)"; then
    _token=$(grep token /etc/gitlab-runner/config.toml | awk -F= '{print substr($2,3,8)}')
    if grep runners.custom /etc/gitlab-runner/config.toml; then
        runner="lxd"
    elif grep runners.docker ; then
        runner="lxd"
    else
        runner="unknown"
    fi
    status-set active "Ready ($runner:$_token)"
    
else
  if check_mandatory_config_values; then
    status-set waiting "Runner not registered in config.toml"
  else
    status-set blocked "Missing config: token or server"
  fi
fi

set-gitlab-runner-version
check_mandatory_config_values
